### ISSUE TITLE
fatal: missing class_of for T_ATTR_REF

### ISSUE THREAD

**Issue by avelure** [nickg/nvc#517]
I get the following when running a TB with UVVM
It is a very large testbench, so it will be a bit difficult to narrow it down to an MWE
```
fatal: missing class_of for T_ATTR_REF
[00007FF687E16340]
[00007FF687E5CBB8]
[00007FF687E47316]
[00007FF687E4AC37]
[00007FF687E5047C]
[00007FF687E30BF5]
[00007FF687E302D0]
[00007FF687E35D7E]
[00007FF687E373C9]
[00007FF687E3875E]
[00007FF687E3B3C8]
[00007FF687E1296C]
[00007FF687EF0CA2] vhpi_put_data+0x22a22
[00007FF687E113AE]
[00007FF687E114E6]
[00007FFB8D5D7034] BaseThreadInitThunk+0x14
[00007FFB8DDA2651] RtlUserThreadStart+0x21

Thread 1 hit Breakpoint 1, 0x00007ffb8b6603e0 in ucrtbase!exit () from /c/Windows/System32/ucrtbase.dll
(gdb) bt
#0  0x00007ffb8b6603e0 in ucrtbase!exit () from /c/Windows/System32/ucrtbase.dll
#1  0x00007ff687e15028 in fatal_exit (status=1) at ../src/util.c:460
#2  0x00007ff687e1634a in fatal_trace (fmt=fmt@entry=0x7ff687f03645 <has_map+25317> "missing class_of for %s") at ../src/util.c:537
#3  0x00007ff687e5cbb8 in class_of (t=<optimized out>) at ../src/common.c:524
#4  0x00007ff687e47316 in sem_check_signal_attr (t=0x224a399d8b0) at ../src/sem.c:3289
#5  0x00007ff687e4ac37 in sem_check_call_args (t=t@entry=0x224a399d750, decl=decl@entry=0x224a25a5f70, tab=tab@entry=0x224a0c1fb20) at ../src/sem.c:2490
#6  0x00007ff687e5047c in sem_check_pcall (t=0x224a399d750, tab=0x224a0c1fb20) at ../src/sem.c:2631
#7  0x00007ff687e30bf5 in p_procedure_call_statement (name=0x224a399d710, label=<optimized out>) at ../src/parse.c:8970
#8  p_sequential_statement () at ../src/parse.c:9138
#9  p_sequence_of_statements (parent=parent@entry=0x224a398ac10) at ../src/parse.c:7029
#10 0x00007ff687e302d0 in p_if_statement (label=0x0) at ../src/parse.c:8697
#11 p_sequential_statement () at ../src/parse.c:9078
#12 p_sequence_of_statements (parent=parent@entry=0x224a36adb70) at ../src/parse.c:7029
#13 0x00007ff687e35d7e in p_process_statement_part (proc=0x224a36adb70) at ../src/parse.c:7208
#14 p_process_statement (label=label@entry=0x224a27e7e70) at ../src/parse.c:7270
#15 0x00007ff687e373c9 in p_concurrent_statement () at ../src/parse.c:9844
#16 0x00007ff687e3875e in p_architecture_statement_part (arch=0x224a36a0000) at ../src/parse.c:9899
#17 p_architecture_body (unit=0x224a36a0000) at ../src/parse.c:9960
#18 p_secondary_unit (unit=unit@entry=0x224a36a0000) at ../src/parse.c:10140
#19 0x00007ff687e3b3c8 in p_library_unit (unit=0x224a36a0000) at ../src/parse.c:10166
#20 p_design_unit () at ../src/parse.c:10222
#21 parse () at ../src/parse.c:10239
#22 0x00007ff687e1296c in analyse (argv=0x2249985adf0, argc=4) at ../src/nvc.c:152
#23 process_command (argc=argc@entry=4, argv=argv@entry=0x2249985adf0) at ../src/nvc.c:1044
#24 0x00007ff687ef0ca2 in main (argc=4, argv=0x2249985adf0) at ../src/nvc.c:1163
```

**Comment by nickg** [comment]
I managed to reproduce this from the stack trace, thanks. Should be fixed now.
